// Code generated by "stringer -type=Feed -linecomment"; DO NOT EDIT.

package feed

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OneForgeXAUETH-1]
	_ = x[OneForgeXAUUSD-2]
	_ = x[GDAXETHUSD-3]
	_ = x[KrakenETHUSD-4]
	_ = x[GeminiETHUSD-5]
	_ = x[CoinbaseETHBTC3-6]
	_ = x[BinanceETHBTC3-7]
	_ = x[CoinbaseETHUSDDAI5000-8]
}

const _Feed_name = "OneForgeXAUETHOneForgeXAUUSDGDAXETHUSDKrakenETHUSDGeminiETHUSDCoinbaseETHBTC3BinanceETHBTC3CoinbaseETHUSDDAI5000"

var _Feed_index = [...]uint8{0, 14, 28, 38, 50, 62, 77, 91, 112}

func (i Feed) String() string {
	i -= 1
	if i < 0 || i >= Feed(len(_Feed_index)-1) {
		return "Feed(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Feed_name[_Feed_index[i]:_Feed_index[i+1]]
}
