// Code generated by "stringer -type=Feed -linecomment"; DO NOT EDIT.

package feed

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GoldData-1]
	_ = x[OneForgeXAUETH-2]
	_ = x[OneForgeXAUUSD-3]
	_ = x[GDAXETHUSD-4]
	_ = x[KrakenETHUSD-5]
	_ = x[GeminiETHUSD-6]
	_ = x[CoinbaseETHBTC3-7]
	_ = x[BinanceETHBTC3-8]
	_ = x[CoinbaseETHDAI10000-9]
	_ = x[KrakenETHDAI10000-10]
}

const _Feed_name = "GoldDataOneForgeXAUETHOneForgeXAUUSDGDAXETHUSDKrakenETHUSDGeminiETHUSDCoinbaseETHBTCC3BinanceETHBTC3CoinbaseETHDAI10000KarakenETHDAI10000"

var _Feed_index = [...]uint8{0, 8, 22, 36, 46, 58, 70, 86, 100, 119, 137}

func (i Feed) String() string {
	i -= 1
	if i < 0 || i >= Feed(len(_Feed_index)-1) {
		return "Feed(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Feed_name[_Feed_index[i]:_Feed_index[i+1]]
}
