// Code generated by "stringer -type=PendingObjectType -linecomment"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PendingTypeUnknown-0]
	_ = x[PendingTypeCreateAsset-1]
	_ = x[PendingTypeUpdateAsset-2]
	_ = x[PendingTypeCreateAssetExchange-3]
	_ = x[PendingTypeUpdateAssetExchange-4]
	_ = x[PendingTypeCreateTradingPair-5]
	_ = x[PendingTypeUpdateTradingPair-6]
	_ = x[PendingTypeCreateTradingBy-7]
	_ = x[PendingTypeUpdateExchange-8]
	_ = x[PendingTypeChangeAssetAddr-9]
}

const _PendingObjectType_name = "unknowncreate_assetupdate_assetcreate_asset_exchangeupdate_asset_exchangecreate_trading_pairupdate_trading_paircreate_trading_byupdate_exchangechange_asset_addr"

var _PendingObjectType_index = [...]uint8{0, 7, 19, 31, 52, 73, 92, 111, 128, 143, 160}

func (i PendingObjectType) String() string {
	if i < 0 || i >= PendingObjectType(len(_PendingObjectType_index)-1) {
		return "PendingObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PendingObjectType_name[_PendingObjectType_index[i]:_PendingObjectType_index[i+1]]
}
