// Code generated by "stringer -type=AddressName -linecomment"; DO NOT EDIT.

package settings

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Reserve-0]
	_ = x[Network-1]
	_ = x[Wrapper-2]
	_ = x[Pricing-3]
	_ = x[InternalNetwork-4]
}

const _AddressName_name = "reservenetworkwrapperpricinginternal_network"

var _AddressName_index = [...]uint8{0, 7, 14, 21, 28, 44}

func (i AddressName) String() string {
	if i < 0 || i >= AddressName(len(_AddressName_index)-1) {
		return "AddressName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddressName_name[_AddressName_index[i]:_AddressName_index[i+1]]
}
