// Code generated by "stringer -type=Feed -linecomment"; DO NOT EDIT.

package world

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GoldData-1]
	_ = x[OneForgeXAUETH-2]
	_ = x[OneForgeXAUUSD-3]
	_ = x[GDAXETHUSD-4]
	_ = x[KrakenETHUSD-5]
	_ = x[GeminiETHUSD-6]
	_ = x[CoinbaseETHBTC-7]
	_ = x[GeminiETHBTC-8]
	_ = x[CoinbaseETHUSDC-9]
	_ = x[BinanceETHUSDC-10]
	_ = x[CoinbaseETHUSD-11]
	_ = x[CoinbaseETHDAI-12]
	_ = x[HitBTCETHDAI-13]
	_ = x[BitFinexETHUSDT-14]
	_ = x[BinanceETHUSDT-15]
	_ = x[BinanceETHPAX-16]
	_ = x[BinanceETHTUSD-17]
}

const _Feed_name = "GoldDataOneForgeXAUETHOneForgeXAUUSDGDAXETHUSDKrakenETHUSDGeminiETHUSDCoinbaseETHBTCGeminiETHBTCCoinbaseETHUSDCBinanceETHUSDCCoinbaseETHUSDCoinbaseETHDAIHitBTCETHDAIBitFinexETHUSDTBinanceETHUSDTBinanceETHPAXBinanceETHTUSD"

var _Feed_index = [...]uint8{0, 8, 22, 36, 46, 58, 70, 84, 96, 111, 125, 139, 153, 165, 180, 194, 207, 221}

func (i Feed) String() string {
	i -= 1
	if i < 0 || i >= Feed(len(_Feed_index)-1) {
		return "Feed(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Feed_name[_Feed_index[i]:_Feed_index[i+1]]
}
