// Code generated by "stringer -type=Mode -linecomment"; DO NOT EDIT.

package mode

import "strconv"

const _Mode_name = "developproduction"

var _Mode_index = [...]uint8{0, 7, 17}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
