FROM golang:1.13-stretch AS build-env

COPY . /reserve-data
WORKDIR /reserve-data/feed-provider/cmd
RUN go build -v -mod=vendor -o /feed-provider

FROM debian:stretch
COPY --from=build-env /feed-provider /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/feed-provider"]
