FROM golang:1.12-stretch AS build-env

COPY . /reserve-data
WORKDIR /reserve-data/reservesetting/cmd
RUN go build -v -mod=vendor -o /setting

FROM debian:stretch
COPY --from=build-env /setting /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV HTTP_ADDRESS=0.0.0.0:8005
EXPOSE 8005
ENTRYPOINT ["/setting"]
