FROM golang:1.13-stretch AS build-env

COPY . /reserve-data
WORKDIR /reserve-data/reservesetting/cmd
RUN go build -v -mod=vendor -o /setting

FROM debian:stretch
COPY --from=build-env /setting /

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/setting"]
