package common

const (
	MiningStatusMined       = "mined"
	MiningStatusFailed      = "failed"
	MiningStatusSubmitted   = "submitted"
	MiningStatusLost        = "lost"
	MiningStatusPending     = "pending"
	ExchangeStatusDone      = "done"
	ExchangeStatusPending   = "pending"
	ExchangeStatusFailed    = "failed"
	ExchangeStatusSubmitted = "submitted"
	ExchangeStatusLost      = "lost"
	ActionDeposit           = "deposit"
	ActionTrade             = "trade"
	ActionWithdraw          = "withdraw"
	ActionSetRate           = "set_rates"
)

const (
	ResultGasPrice    = "gasPrice"
	ResultNonce       = "nonce"
	ResultTx          = "tx"
	ResultError       = "error"
	ResultID          = "id"
	ResultDone        = "done"
	ResultRemaining   = "remaining"
	ResultFinished    = "finished"
	ResultStatusError = "status_error"
	ResultBlockNumber = "blockNumber"
	ResultCanceled    = "canceled"
	WithdrawFee       = "withdraw_fee"
	ParamBase         = "base"
	ParamExchange     = "exchange"
	ParamToken        = "token"
	ParamAmount       = "amount"
	ParamTimepoint    = "timepoint"
	ParamTokens       = "tokens"
	ParamType         = "type"
	ParamQuote        = "quote"
	ParamRate         = "rate"
	ParamBuys         = "buys"
	ParamSells        = "sells"
	ParamBlock        = "block"
	ParamAfpMid       = "afpMid"
	ParamMsgs         = "msgs"
)
